import { Tournament } from "./types";

export const mockTournaments: Tournament[] = [
  {
    id: "t1",
    name: "Spring Basketball Championship",
    sport: "Basketball",
    description: "Annual 5v5 basketball tournament featuring the best local teams competing for the championship title and a $5,000 prize pool.",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    registrationDeadline: "2026-03-10",
    maxTeams: 16,
    registeredTeams: 12,
    entryFee: 250,
    prizePool: 5000,
    status: "registration_open",
    rules: ["5v5 format", "4 quarters of 10 minutes", "NBA rules apply", "Minimum 8 players per roster"],
    facilityId: "f1",
    facilityName: "Championship Court",
    imageUrl: "/placeholder.svg",
  },
  {
    id: "t2",
    name: "Indoor Soccer League",
    sport: "Soccer",
    description: "8-week indoor soccer league with round-robin format followed by playoffs. Open to all skill levels.",
    startDate: "2026-04-01",
    endDate: "2026-05-24",
    registrationDeadline: "2026-03-25",
    maxTeams: 12,
    registeredTeams: 8,
    entryFee: 400,
    prizePool: 3000,
    status: "registration_open",
    rules: ["6v6 format", "2 halves of 25 minutes", "Modified FIFA rules", "No slide tackles"],
    facilityId: "f2",
    facilityName: "Premier Soccer Pitch",
    imageUrl: "/placeholder.svg",
  },
  {
    id: "t3",
    name: "Tennis Singles Open",
    sport: "Tennis",
    description: "Open singles tennis tournament with bracket-style elimination. All skill levels welcome.",
    startDate: "2026-03-01",
    endDate: "2026-03-08",
    registrationDeadline: "2026-02-25",
    maxTeams: 32,
    registeredTeams: 32,
    entryFee: 75,
    prizePool: 1500,
    status: "registration_closed",
    rules: ["Best of 3 sets", "ITF rules", "Players provide own rackets"],
    facilityId: "f3",
    facilityName: "Ace Tennis Center",
    imageUrl: "/placeholder.svg",
  },
  {
    id: "t4",
    name: "Summer Volleyball Smash",
    sport: "Volleyball",
    description: "Exciting beach volleyball tournament with teams of 4. Cash prizes and trophies for top 3 teams.",
    startDate: "2026-06-10",
    endDate: "2026-06-12",
    registrationDeadline: "2026-06-01",
    maxTeams: 24,
    registeredTeams: 6,
    entryFee: 150,
    prizePool: 2000,
    status: "upcoming",
    rules: ["4v4 format", "Rally scoring to 25", "FIVB rules"],
    facilityId: "f5",
    facilityName: "Volleyball Arena",
    imageUrl: "/placeholder.svg",
  },
];
